export type Service = {
  slug: string;
  name: string;
  tier: "starter" | "growth" | "scale" | "premium";
  setupPrice: string;
  monthlyPrice: string;
  deliveryDays: string;
  idealFor: string;
  pain: string;
  deliverables: string[];
  referenceClient?: string;
  icon: string; // Lucide icon name
};

export const services: Service[] = [
  // --- Proven (live clients) ---
  {
    slug: "order-automation",
    name: "Order-to-Delivery Automation",
    tier: "growth",
    setupPrice: "£1,500",
    monthlyPrice: "£150/mo",
    deliveryDays: "7-10 days",
    idealFor: "Food businesses, bakeries, caterers",
    pain: "Manual order collection, payment chasing",
    deliverables: [
      "Online order form",
      "Production dashboard",
      "Payment matching",
      "Delivery route optimisation",
      "WhatsApp alerts",
      "9 workflows",
    ],
    referenceClient: "E'Manuel Bakery",
    icon: "ShoppingCart",
  },
  {
    slug: "business-website",
    name: "Professional Business Website",
    tier: "growth",
    setupPrice: "£1,500",
    monthlyPrice: "£150/mo",
    deliveryDays: "10-14 days",
    idealFor: "Churches, charities, local businesses",
    pain: "No/outdated website",
    deliverables: [
      "Custom responsive site",
      "Brand identity",
      "8-12 pages",
      "Contact forms",
      "SEO baseline",
      "Domain email",
      "SSL",
    ],
    referenceClient: "QuantumFM Media",
    icon: "Globe",
  },

  // --- Ready to deploy ---
  {
    slug: "lead-intake",
    name: "AI Lead Intake & Appointment Booking",
    tier: "starter",
    setupPrice: "£500",
    monthlyPrice: "£50/mo",
    deliveryDays: "5-7 days",
    idealFor: "Plumbers, cleaners, salons, gyms",
    pain: "Missing leads, slow response",
    deliverables: [
      "Lead capture form",
      "AI qualification",
      "Calendar booking",
      "Follow-up sequences",
      "KPI dashboard",
    ],
    referenceClient: undefined,
    icon: "CalendarCheck",
  },
  {
    slug: "whatsapp-bot",
    name: "WhatsApp Customer Bot",
    tier: "growth",
    setupPrice: "£1,500",
    monthlyPrice: "£150/mo",
    deliveryDays: "7-10 days",
    idealFor: "Restaurants, takeaways, salons",
    pain: "Manual WhatsApp replies",
    deliverables: [
      "WhatsApp API bot",
      "Order-taking",
      "FAQ handling",
      "Payment links",
      "Human handoff",
    ],
    referenceClient: undefined,
    icon: "MessageCircle",
  },
  {
    slug: "email-assistant",
    name: "AI Email Assistant",
    tier: "starter",
    setupPrice: "£500",
    monthlyPrice: "£50/mo",
    deliveryDays: "3-5 days",
    idealFor: "Consultants, agencies, tradespeople",
    pain: "Drowning in emails",
    deliverables: [
      "AI-drafted replies",
      "Learns tone",
      "Handles enquiries/quotes/scheduling",
    ],
    referenceClient: undefined,
    icon: "Mail",
  },
  {
    slug: "seo-content",
    name: "SEO Content Automation",
    tier: "starter",
    setupPrice: "£500",
    monthlyPrice: "£50/mo",
    deliveryDays: "5-7 days",
    idealFor: "Local service businesses",
    pain: "Invisible on Google",
    deliverables: [
      "AI keyword research",
      "2-4 posts/month",
      "Local SEO pages",
      "WordPress auto-publish",
      "Monthly report",
    ],
    referenceClient: undefined,
    icon: "Search",
  },
  {
    slug: "social-media",
    name: "Social Media Content Engine",
    tier: "starter",
    setupPrice: "£500",
    monthlyPrice: "£50/mo",
    deliveryDays: "3-5 days",
    idealFor: "Coaches, personal brands, restaurants",
    pain: "No time for social media",
    deliverables: [
      "Content repurposing",
      "AI captions",
      "Multi-platform formatting",
    ],
    referenceClient: undefined,
    icon: "Share2",
  },
  {
    slug: "lead-scraping",
    name: "Lead Scraping & Enrichment",
    tier: "starter",
    setupPrice: "£500",
    monthlyPrice: "£50/mo",
    deliveryDays: "5-7 days",
    idealFor: "B2B services, recruitment, marketing agencies",
    pain: "Manual prospect research",
    deliverables: [
      "Web scraping",
      "Data enrichment",
      "AI lead scoring",
      "Clean CSV output",
    ],
    referenceClient: undefined,
    icon: "Database",
  },
  {
    slug: "voice-assistant",
    name: "Voice Assistant Agent",
    tier: "starter",
    setupPrice: "£500",
    monthlyPrice: "£50/mo",
    deliveryDays: "5-7 days",
    idealFor: "Solo practitioners, clinics, tutors",
    pain: "Missing calls, no after-hours",
    deliverables: [
      "AI phone/Telegram agent",
      "Calendar booking",
      "FAQ handling",
      "Human escalation",
    ],
    referenceClient: undefined,
    icon: "Phone",
  },
  {
    slug: "ai-workshop",
    name: "AI Workshop for Teams",
    tier: "premium",
    setupPrice: "£500-5,000",
    monthlyPrice: "per session",
    deliveryDays: "2-4 hours",
    idealFor: "SMB teams of 5-50",
    pain: "Know AI exists but haven't adopted",
    deliverables: [
      "In-person or virtual",
      "Hands-on",
      "Industry-tailored",
    ],
    referenceClient: undefined,
    icon: "GraduationCap",
  },
  {
    slug: "ai-audit",
    name: "AI Readiness Audit",
    tier: "premium",
    setupPrice: "£150",
    monthlyPrice: "one-time",
    deliveryDays: "48 hours",
    idealFor: "Any prospect",
    pain: "Unsure where AI fits",
    deliverables: [
      "5-section report",
      "Business snapshot",
      "AI opportunity map",
      "ROI projection",
      "Recommended solution",
    ],
    referenceClient: undefined,
    icon: "FileSearch",
  },
  {
    slug: "custom-build",
    name: "Custom Automation Build",
    tier: "premium",
    setupPrice: "from £500",
    monthlyPrice: "quoted",
    deliveryDays: "1-3 weeks",
    idealFor: "Businesses with unique problems",
    pain: "Unique workflow problems",
    deliverables: [
      "Audit first",
      "Custom proposal",
      "Bespoke build",
    ],
    referenceClient: undefined,
    icon: "Wrench",
  },
];

export const servicesByTier = {
  starter: services.filter((s) => s.tier === "starter"),
  growth: services.filter((s) => s.tier === "growth"),
  scale: services.filter((s) => s.tier === "scale"),
  premium: services.filter((s) => s.tier === "premium"),
};
